name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Déclenche l'action lorsque du code est poussé sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu pour exécuter l'action

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Vérifie le code du repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configure Docker Buildx pour la construction multi-plateforme

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v2
        with:
          username: "mohatgh"  # Utilise l'utilisateur GitHub comme identifiant
          password: "moha2002"  # Utilise le jeton GitHub par défaut pour l'authentification

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  # Spécifie le contexte de la construction, ici le répertoire courant
          push: true  # Publie l'image après la construction
          tags: ghcr.io/${{ github.repository }}:latest   # Utilise le nom du repository GitHub comme tag pour l'image
